### ISSUE TITLE
Codes SMTP (ZAM^Z02^ZAM_Z02)

### ISSUE THREAD

**Issue by mlr-kereval** [ansforge/hl7V2-exemples#11]
Ajouter en annexe des spécifications la liste des codes permis pour le champ ERR-5 du message ZAM^Z03^ZAM_Z03 (codes SMTP ou codes erreurs de la MSSanté)

**Comment by isa-ans** [comment]
Abandon si nous décidons de demander un retour d'expérience des éditeurs sur le sujet des accusés de lecture.

**Comment by isa-ans** [comment]
Proposition d'une liste de codes par Morane. Attendre le retour des éditeurs

**Comment by isa-ans** [comment]
OK
