### ISSUE TITLE
Modification du profil de message ORU (volet (1) HL7_CDA)

### ISSUE THREAD

**Issue by isa-ans** [ansforge/hl7V2-exemples#14]
- Les segments ORC et OBR deviennent obligatoires (harmonisation avec le message MDM)
- le champ MSH-18 peut prendre les 2 valeurs UNICODE-UTF8 ou 8859/15 quelle que soit la version d'HL7 (cf IHE PAM internationnal)
- suppression du segment SPECIMEN, DSC

**Comment by mlr-kereval** [comment]
Validateur ORU^R01^ORU_R01 mis à jour : 

- Segments ORC et OBR -> Required 
- MSH-18 = UNICODE-UTF8 ou 8859/15
- Groupe SPM et segment DSC -> Not supported

**Comment by isa-ans** [comment]
- **Validateur ORU^R01^ORU_R01**: en cas d'absence des segments ORC ou OBR le message d'erreur indique pour chaque segment du message :" is not expected at this location" en affichant en particulier la base 64 du 1° OBX.
Le message d'erreur devrait plutôt être : segment OBR manquant ou segment ORC manquant.
- MSH-18 = UNICODE-UTF8 ou 8859/15 --> OK
- Groupe SPM et segment DSC -> Not supported -->OK
