### ISSUE TITLE
Evolution MSH-18 (volet (1) HL7_CDA)

### ISSUE THREAD

**Issue by isa-ans** [ansforge/hl7V2-exemples#15]
le champ MSH-18 peut contenir UNICODE-UTF8 ou 8859/15 quelle que soit la version d'HL7

**Comment by mlr-kereval** [comment]
Validateurs ORU^R01^ORU_R01, ACK 2.5 et ACK 2.6 mis à jour :

- MSH-18 = UNICODE-UTF8 ou 8859/15

**Comment by isa-ans** [comment]
OK
