### ISSUE TITLE
Evolution MSH-21 (volet (1) HL7_CDA)

### ISSUE THREAD

**Issue by isa-ans** [ansforge/hl7V2-exemples#16]
- Modification de la valeur MSH-21.1 qui devient 2.1 (au lieu de 2.0) pour le volet 1 et 1.1 pour le volet 2

**Comment by mlr-kereval** [comment]
Au niveau des validateurs du volet 1 (ORU, MDM et ZAM), MSH-21.1 = 2.1
Au niveau des validateurs du volet 2 (MDM), MSH-21.1 = 1.1
