### ISSUE TITLE
Cohérence ORC-1 et OBX-11 du message ORU/MSH-9 du message MDM (volet (1) HL7_CDA)

### ISSUE THREAD

**Issue by isa-ans** [ansforge/hl7V2-exemples#17]
Vérifier la cohérence entre la valeur ORC-1 et OBX-11 du message ORU ou MSH-9 du message MDM

**Comment by mlr-kereval** [comment]
Les validateurs ORU et MDM contiennent les contraintes suivantes :

- ORC-1 = NW -> OBX-11 = F (pour l'OBX contenant le document CDA) + MSH-9.2 = T02 dans le cadre du MDM
- ORC-1 = RO -> OBX-11 = C (pour l'OBX contenant le document CDA) + MSH-9.2 = T10 dans le cadre du MDM
- ORC-1 = CA-> OBX-11 = D (pour l'OBX contenant le document CDA) + MSH-9.2 = T04 dans le cadre du MDM
