### ISSUE TITLE
Evolution message ZAM^Z01 (accusé réception DMP)

### ISSUE THREAD

**Issue by isa-ans** [ansforge/hl7V2-exemples#21]
- MSH-21=2.1
- OBX portant le statut de l'accusé: ajout OBX-1 (séquence), OBX-5.3 (remplacement HL70136 par expandedYes-NoIndicator)
- ERR-3.3 : remplacer HL70357 par MessageErrorCondition

**Comment by mlr-kereval** [comment]
Validateur ZAM^Z01^ZAM_Z01 mis à jour : 

- OBX-5.3 = expandedYes-NoIndicator
- ERR-3.3 = messageErrorCondition

Le champ MSH-21 est bien fixé à 2.1 et OBX-1 est requis.

**Comment by isa-ans** [comment]
OK
