### ISSUE TITLE
Suppression du message ZAM^Z03 (volet 2)

### ISSUE THREAD

**Issue by isa-ans** [ansforge/hl7V2-exemples#24]
Suppression de l'accusé métier ZAM^Z03 dans le volet LPS_MSS (volet 2). L'accusé ACK du message HL7 MDM renvoie l'erreur d'intégration de la demande, si besoin

**Comment by mlr-kereval** [comment]
Validateur ACK 2.6 mis à jour : 

- ERR-3.1 prend ses valeurs dans la table messageErrorCondition / ERR-3.3 = messageErrorCondition 
- ERR-5.1 prend ses valeurs dans la table applicationErrorCode / ERR-5.3 = applicationErrorCode
