### ISSUE TITLE
Métadonnées DMP/MSS obligatoires et ordonnées (volet (2) LPS_MSS)

### ISSUE THREAD

**Issue by isa-ans** [ansforge/hl7V2-exemples#25]
Les métadonnées sont obligatoires (sauf la dernière) et ordonnées
- ajout OBX-1 : séquence de l'OBX
- OBX-3= OBR-4 à vérifier dans le validateur
- PRT-4 : remplacer le nom de la table HL70912 par participation
- PRT-5 et PRT-8 passent en requis si connu

**Comment by mlr-kereval** [comment]
Le champs OBX-1 est requis et l'ordre des segments doit être respecté.

Segments PRT mis à jour : 

- PRT-4.3 = participation
- PRT-5 et PRT-8 -> RE pour les segments représentant le destinataire initial, l'expéditeur à l'origine de la demande

**Comment by isa-ans** [comment]
Vérifié -->OK
