### ISSUE TITLE
Evolution de l'OBX portant les informations du courriel (volet (2) LPS_MSS)

### ISSUE THREAD

**Issue by isa-ans** [ansforge/hl7V2-exemples#26]
- ajout de la séquence OBX-1
- OBX-5 codé en base 64
- suppression de l'OBX métadonnée demande d'accusé de lecture MSS

**Comment by mlr-kereval** [comment]
Validateurs MDM mis à jour : 

- Suppression du segment OBX représentant l'accusé de lecture MSSanté

Le champs OBX-1 est requis et OBX-5.4 = Base64 pour le segment portant les informations du courriel MSSanté.
