### ISSUE TITLE
Message ACK ( (volet (1) HL7_CDA)olet (2) LPS_MSS)

### ISSUE THREAD

**Issue by isa-ans** [ansforge/hl7V2-exemples#27]
Segment ERR : vérification par le validateur du code erreur par rapport aux valeurs contenues dans la table des codes erreurs de traitement du message MDM

**Comment by mlr-kereval** [comment]
Validateur ACK 2.6 mis à jour :

    ERR-3.1 prend ses valeurs dans la table messageErrorCondition / ERR-3.3 = messageErrorCondition
    ERR-5.1 prend ses valeurs dans la table applicationErrorCode / ERR-5.3 = applicationErrorCode

**Comment by isa-ans** [comment]
Vérifié -->OK
