### ISSUE TITLE
Identification document et document parent (TXA-12 et TXA-13)

### ISSUE THREAD

**Issue by isa-ans** [ansforge/hl7V2-exemples#33]
page 28 section 12.2.5 lignes TXA-12 et TXA-13. Il pourrait être utile d’expliquer plus en détail comment on renseigne ces éléments à partir des données du document CDA. En particulier, il nous semble difficile de peupler de manière cohérente entre les différents systèmes le TXA-12.2 et TXA-13.2 dans la mesure où cet élément ne vient pas du CDA. Proposition de règle de peuplement à partir du CDA (vaut pour les composants du TXA-13 aussi):

    si ClinicalDocument/id@extension est renseigné :
        TXA-12.1 < = ClinicalDocument/id@extension
        TXA-12.2 < = Non renseigné
        TXA-12.3 < = ClinicalDocument/id@root
        TXA-12.4 < = ISO

    si ClinicalDocument/id@extension n’est pas renseigné :
        TXA-12.1 < = ClinicalDocument/id@root
        TXA-12.2 < = Non renseigné
        TXA-12.3 < = Non renseigné
        TXA-12.4 < = Non renseigné

Analyse : le DMP ne supporte pas le format OID/extension, seul le format ClinicalDocument/id@root est géré. Suppression des sous champs TXA-12.2, TXA-12.3 et TXA-12.4
Les validateurs seront peut-être à modifier en conséquence

**Comment by isa-ans** [comment]
Modification de la spécification des champs TXA-12 et TXA-13 sur les 2 volets et modification des validateurs si besoin

**Comment by isa-ans** [comment]
cf ci-dessus

**Comment by isa-ans** [comment]
modification du titre de la CP

**Comment by mlr-kereval** [comment]
Le cross-validateur "CROSS_VALIDATEUR_HL7v2_CDA" a été mis à jour pour contrôler le TXA-12 et TXA-13.

**Comment by isa-ans** [comment]
Vérifié -->OK
