### ISSUE TITLE
Augmentation de la taille du champ TXA-12.1

### ISSUE THREAD

**Issue by isa-ans** [ansforge/hl7V2-exemples#4]
Prévoir l'augmentation de la taille du champ TXA-12.1 sur le message MDM

**Comment by mlr-kereval** [comment]
Proposition : augmenter également la taille des champs TXA-13.1, TXA-16, MSH-3.1, MSH-4.1, MSH-6.1, MSH-5.1, OBX-3.1, OBX-4

**Comment by mlr-kereval** [comment]
Je propose d'augmenter la taille de ces champs car ils ont retournés des warning lors du PAT : 

- MSH-4.1, TXA-12.1, TXA-13.1 : https://interop.esante.gouv.fr/evs/hl7v2Result.seam?oid=1.3.6.1.4.1.12559.11.36.4.22589
- MSH-6.1 : https://interop.esante.gouv.fr/evs/hl7v2Result.seam?oid=1.3.6.1.4.1.12559.11.36.4.23551
- OBX-3.1,TXA-16, MSH-5.1 : https://interop.esante.gouv.fr/evs/hl7v2Result.seam?oid=1.3.6.1.4.1.12559.11.36.4.23861
- OBX-4 : https://interop.esante.gouv.fr/evs/hl7v2Result.seam?oid=1.3.6.1.4.1.12559.11.36.4.24376

**Comment by isa-ans** [comment]
- TXA-12.1 et TXA-13.1 : OK, requis pour l'évènement T10
- les MSH: OK
- OBX-4 des messages métiers ZAM : OK
je n'accède pas à ce test : OBX-3.1,TXA-16, MSH-5.1 : https://interop.esante.gouv.fr/evs/hl7v2Result.seam?oid=1.3.6.1.4.1.12559.11.36.4.23861 

Il faudra préciser la longueur de ces champs sur les specs des 2 volets et modifier les validateurs en fonction.
