### ISSUE TITLE
CDA_HL7v2 / Modification des profils de message ORU et MDM

### ISSUE THREAD

**Issue by isa-ans** [ansforge/hl7V2-exemples#42]
Modification du profil des messages ORU et MDM: tableau 12.1.1.1 et 12.1.2.1

le PRT associé à l'OBX portant le(s) document(s) était indiqué comme étant optionnel.
En réalité il doit exister au moins un PRT (au moins l'expéditeur en cas de publication sur le DMP et au moins un destinataire en cas d'échange vis MSSanté)
En conséquence, le PRT est passé en Requis et conditionnel, sa cardinalités passe à [1..*]

**Comment by mlr-kereval** [comment]
> Après test sur un ORU ou un MDM en supprimant tous les PRT, le message est valide. Le validateur ne vérifie pas l'existence d'au moins un PRT --> à corriger

Les validateurs ORU et MDM ont été corrigé afin de remonter une erreur si le premier groupe OBSERVATION ne contient aucun segment PRT.

**Comment by sdemeyANS** [comment]
> > Après test sur un ORU ou un MDM en supprimant tous les PRT, le message est valide. Le validateur ne vérifie pas l'existence d'au moins un PRT --> à corriger
> 
> Les validateurs ORU et MDM ont été corrigé afin de remonter une erreur si le premier groupe OBSERVATION ne contient aucun segment PRT.

@mlr-kereval du coup l'issue peut être closed?
