### ISSUE TITLE
CDA_HL7v2 : ajout du champ ERR-5 au message ZAM_Z03

### ISSUE THREAD

**Issue by isa-ans** [ansforge/hl7V2-exemples#44]
- Ajout du champ ERR-5 au message ZAM_Z03 pour remonter les erreurs applicatives du traitement de la demande au niveau du destinataire final du courriel (CONSOMMATEUR)

**Comment by mlr-kereval** [comment]
Bonjour @isa-ans, 

Nous venons de remarquer une erreur de typo dans le nom donné à la table HL70533. Il est noté "applicationErrorCode" comme nom symbolique or dans l'exemple ERR-5.3 prend la valeur "applicationErrorCondition". 
Quelle valeur devons-nous attribuer à ERR-5.3 ?

**Comment by isa-ans** [comment]
typo corrigée
