### ISSUE TITLE
message_ORU [PRT-5]

### ISSUE THREAD

**Issue by M-Priour** [ansforge/hl7V2-exemples#47]
- [https://github.com/ansforge/hl7V2-exemples/blob/e98ede1195955094f403a3548967aa1b4ae754f6/Vague%202/Trans_Doc-CDA-HL7V2/TRANSMISSION_DOCS_CDA_EN_HL7V2_V2.1/ORU/Transmission%20initiale%20ORU/SEGUR%20vague%202/message_ORU_CR_Bio_INIT_N3_SEGUR.hl7](url)

- https://github.com/ansforge/hl7V2-exemples/blob/e98ede1195955094f403a3548967aa1b4ae754f6/Vague%202/Trans_Doc-CDA-HL7V2/TRANSMISSION_DOCS_CDA_EN_HL7V2_V2.1/ORU/Remplacement%20ORU/SEGUR%20vague%202/message_ORU_CR_Bio_RPLC_N3_SEGUR.hl7

- https://github.com/ansforge/hl7V2-exemples/blob/e98ede1195955094f403a3548967aa1b4ae754f6/Vague%202/Trans_Doc-CDA-HL7V2/TRANSMISSION_DOCS_CDA_EN_HL7V2_V2.1/ORU/Suppression%20ORU/SEGUR%20vague%202/message_ORU_CR_Bio_DEL_N3_SEGUR.hl7

Pour ces message, au regard du validateur et des spécifications, le champ PRT-5 devrait être pour l'envoi au patient : 
PRT||UC||RCT^^participation|277076322082910^NESSI^RUTH^^^^^^^L^^^INS||||||||||^^X.400^2770763220829106@patient.mssante.fr

**Comment by M-Priour** [comment]
Par contre quand, on enleve le champ PRT-5, on obtient une erreur sur le PRT-10 : 
https://interop-pprod.esante.gouv.fr/evs/hl7v2Result.seam?oid=2.16.840.1.113883.2.7.4.4818

**Comment by isa-ans** [comment]
Correction sur PRT-5 réalisée : modification du nom/prénom du patient, modification de l'INS du patient et ajout de l'OID de l'autorité d'affectation de l'INS du patient
