### ISSUE TITLE
Exemple Ségur avec extension

### ISSUE THREAD

**Issue by M-Priour** [ansforge/hl7V2-exemples#49]
L'exemple ci-dessous contient une extension pour identifier le document : 
- https://github.com/ansforge/hl7V2-exemples/blob/7a946ade1c8bf2dc7164d4c3e48b175963014804/Vague%202/Trans_Doc-CDA-HL7V2/TRANSMISSION_DOCS_CDA_EN_HL7V2_V2.1/MDM/Transmission%20initiale%20MDM/message_MDM_CR_Radio_INIT_N1_Base64.er7

Il faudrait que l'on regarde pour l'enlever.

**Comment by isa-ans** [comment]
Toutes les extensions sur l'id de documents ont été supprimées sur l'ensemble des exemples
